version: '3'
services:
  test:
    image: quay.io/podman/stable
    command:
    - /bin/sh
    - "-c"
    - |
      podman --log-level=debug run -it alpine echo hi
    working_dir: /project
    volumes:
    - .:/project
    devices:
      - "/dev/fuse:/dev/fuse"
