version: '3'
services:
  test:
    build: .
    command:
    - /bin/sh
    - "-c"
    - |
      uv run python -m pytest -svvv ./tests
    working_dir: /project
    privileged: true
    volumes:
    - .:/project
